language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -U mock pytest pytest-mock pytest-cov codecov
script:
  - coverage run --source=ssdpy,tests -m pytest tests/

after_success:
  - codecov

branches:
  only:
    - master
