language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -Ur dev-requirements.txt
script:
  - pytest --cov-report=xml --cov=ssdpy
  - codecov

branches:
  only:
    - master
